config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  resources :orders do
    resources:orderitems
  end
  
  
  resources :categories
  
  
  
  devise_for :users do
    resources:orders
  end
  
  get '/checkout', to: 'cart#createOrder'
  
  get '/paid', to: 'static_pages#paid'
  
  
  post '/search', to: 'items#search'
  
  
  #get '/checkout', to: 'cart#index'


  get 'cart/index'


  resources :items
  root 'static_pages#home'

  get '/about', to: 'static_pages#about' 

  get '/contact', to: 'static_pages#contact'
  
  get '/items', to: 'items#items'
 
  get '/login', to: 'user#login'

  get '/logout', to: 'user#logout'

  get '/cart', to: 'cart#index'
  get '/cart/clear', to: 'cart#clearCart'
   
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id', to: 'cart#remove'
  root :to => 'site#home'
  
  get 'category/:title', to: 'static_pages#category'
  
  

end

 
 

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :category
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end
  
  
  def search
  @search_term = params[:q]
  st = "%#{params[:q]}%"
  @items = Item.where("name like ?", st)
  end
  



  # GET /items/1
  # GET /items/1.json
  
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @categories = Category.all.map{|c| [ c.title, c.id ] }
  end

  # GET /items/1/edit
  def edit
     @categories = Category.all.map{|c| [ c.title, c.id ] }
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    @item.category_id = params[:category_id]
    @categories = Category.all.map{|c| [ c.title, c.id ] }

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    @item.category_id = params[:category_id]
    @categories = Category.all.map{|c| [ c.title, c.id ] }
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :category, :caloriesPerServing, :glutenFree, :containsNuts, :description, :image)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
        <% if item.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
      
            <ul>


            <% item.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        
        <div class="field">
          <label>Image</label>
          <%= form.text_field :image, id: :item_image %>
        </div>
        <div class="field">
          <label><b>Name</b></label>
          <%= form.text_field :name, id: :item_name %>
        </div>
        <div class="field">
          <label><b>Price</b></label>
          <%= form.text_field :price, id: :item_price %>
        </div>
        <div class="field">
          <label>Category</label>
           <%= select_tag(:category_id, options_for_select(@categories, :selected => item.category_id), :prompt => 'Select one!' ) %>
          </div>
      
        <div class="field">
          <label>Calories per Serving</label>
          <%= form.number_field :caloriesPerServing, id: :item_caloriesPerServing %>
        </div>
      
        <div class="field">
          <label>Gluten Free</label>
          <%= form.check_box :glutenFree, id: :item_glutenFree , :class => 'gluten' %>
        </div>
      
        <div class="field">
          <label>Contains Nuts</label>
          <%= form.check_box :containsNuts, id: :item_containsNuts , :class => 'nuts' %>
        </div> 
      
        <div class="field">
          <label>Description</label>
          <%= form.text_area :description, id: :item_description %>
        </div>
      
        
        <div class="actions">
          <%= form.submit 'Submit' , :class => 'btn btn-primary'  %>
        </div>
      <% end %>
      </div>   

app/views/items/edit.html.erb
<div class="row">
   <div class="col-md-12 new">
    <div class"container">
       <div class="content">

        <h1>Editing Item</h1>
        
        <%= render 'form', item: @item %>
        
        <%= link_to 'Show', @item %> |
        <%= link_to 'Back', items_path %>
     </div>
   </div>
  </div>
</div>

app/views/items/index.html.erb
  <div class="row page">
  <div class="heading-area">
    <div class="container">
      <div class="content">
          <h1 class="text-center">See full range of our delicious Cakes!</h1>
          <h3 class="text-center">Best bakery at this location.</h3>
      </div>
    </div>
  </div>  
  
 <p id="notice"><%= notice %></p>
  
<div class="row">
  <div class="itemsPage">
    <div class="container">
      <% if admin_signed_in? %>  <!-- only allow admin to add product -->
           <div class="add-item">
              <%= link_to 'New Item', new_item_path, :class=>"btn btn-primary", :role=>"button" %>
            </div>
      <% end %>  
      
      <div class="content body-txt">
         
        
        <% @items.each do |item| %>
         <div class="col-md-3 text-center cake">
             <span class="imgHols">
             <%= link_to (image_tag item.image, :class=>"img-responsive"), item %>
             </span>
                <h3><%= item.name %></h3>
             
                <h4>Price: € <%= item.price %></h4>
                <p><b>Calories per Serving:</b> <%= item.caloriesPerServing %>
                <br><b>Gluten Free: </b>
                <%  if item.glutenFree? %>Yes
                <% else %>No 
                <% end %>
                <br><b>Item contains Nuts: </b>
                <% if item.containsNuts? %>Yes
                <% else %>No 
                <% end %>
                <br>
             <br><%= item.description %></p>
             
            
            
             <a href="/cart/<%= item.id %>" class="btn btn-primary">add to Cart</a>
            
            
               
            <!--   was  if session[:login] == 1  in ruby brackets -->
            <% if admin_signed_in? %>
            <%= link_to 'Show', item, :class=> "show-link" %>
            <%= link_to 'Edit', edit_item_path(item), :class=> "edit-link " %>
            <%= link_to 'Destroy', item, :class=> "delete-link", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>  
            
         </div>
        <% end %>
    </div>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="row">
   <div class="col-md-12 new">
    <div class"container">
       <div class="content">
        <h1>New Item</h1>

        <%= render 'form', item: @item %>
        
        <%= link_to 'Back', items_path %>
    </div>
   </div>
  </div>
</div>

app/views/items/search.html.erb
<p id="notice"><%= notice %></p>




<% if @items.length ==0 %>
<H1 class="py-5 text-center">Your search did not match any results.</h1>
<br>
<H2 class="py-5 text-center">Would you like to try different type of cakes instead?</h2>
<% end %>




<div class="row">
    <% @items.each do |item| %>
    
    
    
 <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 text-center">
    
    <h2><%= item.name %></h2>
        <h4>Price: € <%= item.price %></h4>
        <p>Calories per Serving: <%= item.caloriesPerServing %></p>
        <p>Gluten Free: 
        <%  if item.glutenFree? %>Yes
        <% else %>No 
        <% end %></p>
        <p>Item contains Nuts: 
        <% if item.containsNuts? %>Yes
        <% else %>No 
        <% end %>
        </p>
        <%= link_to (image_tag item.image, :class=>"img-responsive"), item %>
     <p><%= item.description %></p>
    
    <p>
     <a href="/cart/<%= item.id %>" class="btn btn-primary">add to Cart</a>
    
    
       
    <% if session[:login] == 1 %>
    

    <%= link_to 'Edit', edit_item_path(item) %>
    <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
    <%= link_to 'Show', item, :class=>"btn btn-primary" %>
    <% end %>  
    </p>
 </div>
<% end %>
</div>

<br>

<%= link_to 'New Item', new_item_path, :class=>"btn btn-primary", :role=>"button" %>

app/views/items/show.html.erb
<div class="row">
   <div class="col-md-12 new">
    <div class"container">
       <div class="content">

<h3><%= @item.name  %></h3>
<tr>

  <td><img class="img-responsive" src=<%=asset_path @item.image, {:style => "width:10%;"} %>/></td>
</tr>

</div>
<% if notice %>
<div class="alert alert-info">
<p id="notice"><%= notice %></p>
</div>
<% end %>


<table class="table table-bordered">
<tr>
  <td><b>Price:</b></td>
  <td><%= @item.price %></td>
</tr>

<tr>
  <td><b>Category:</b></td>
  <td><%= @item.category %></td>
</tr>

<tr>
  <td><b>Calories per Serving:</b></td>
  <td><%= @item.caloriesPerServing %></td>
</tr>

<tr>
  <td><b>Gluten Free:</b></td>
  <td><%= @item.glutenFree %></td>
</tr>


                
                

<tr>
  <td><b>Gluten Free:</b></td>
	<td>	<% case @item.glutenFree
		when "Yes" %>
		<p>yes</p>
		<% when "No" %>
		<p>no</p>
		<% end %>
	</td>

</tr>
	
	
	


<tr>
  <td><b>Contains Nuts:</b></td>
  <td><%= @item.containsNuts %></td>
</tr>


<tr>
  <td><b>Description:</b></td>
  <td><%= @item.description %></td>
</tr>





</table>

<%= link_to 'Back', items_path, :class=>"btn btn-primary" %>
     </div>
   </div>
  </div>
</div>