config/routes.rb
Rails.application.routes.draw do

  devise_for :admins
  get 'orderitems/index'

  get 'orderitems/show'

  get 'orderitems/new'

  get 'orderitems/edit'

  resources :orders do
    resources:orderitems
  end
  
  
  resources :categories
  
  
  
  devise_for :users do
    resources:orders
  end
  
  get '/checkout', to: 'cart#createOrder'
  
  get '/paid', to: 'static_pages#paid'
  
  
  post '/search', to: 'items#search'
  
  
  #get '/checkout', to: 'cart#index'


  get 'cart/index'


  resources :items
  root 'static_pages#home'

  get '/about', to: 'static_pages#about' 

  get '/contact', to: 'static_pages#contact'
  
  get '/items', to: 'items#items'
 
  get '/login', to: 'user#login'

  get '/logout', to: 'user#logout'

  get '/cart', to: 'cart#index'
  get '/cart/clear', to: 'cart#clearCart'
   
  get '/cart/:id', to: 'cart#add'
  get '/cart/remove/:id', to: 'cart#remove'
  root :to => 'site#home'
  
  get 'category/:title', to: 'static_pages#category'
  
  

end

 
 

app/views/layouts/_categories.html.erb
<% @categories.each do |category| %>
  <div class="col-md-4 text-center cake">
    <%= image_tag category.image, :class=>"img-circle float-left", :style=>"width:200px;height:200px;" %> 
    <h3><%= category.title %></h3>
    <p><%= category.descriprion %></p>
    <a href="/category/<%= category.title %>" class="btn btn-primary">View Category</a>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="row foot">
    <div class="col-md-12">
      <div class="container">
        <% if session[:login] == 1 %>
        <%= link_to 'New Product', new_item_path, :class =>"btn btn-primary", :role=>"button" %>
        <%= link_to 'New Category', new_category_path, :class => "btn btn-primary", :role=>"button" %>
        <% end %>
        
         <% if user_signed_in? %>
        <%= link_to "ViewOrders", orders_path, :class => "btn btn-primary", :role=>"button" %>
          <% end %>
      </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header">
    <div class="headTop">
      <div class="container">
        <table><tr><td class="call-label">Call Us:</td><td class="phone"><a href="tel:1234567">1234567</a></td>
        <td class="search"><%= render 'layouts/search' %></td>
        <td class="admin-link"><ul><% if admin_signed_in? %>
         <li><%= link_to 'Log out', destroy_admin_session_path, :method => :delete %></li>
         <% else %>
         <li><%= link_to 'Log in', new_admin_session_path %></li>
        <% end %></li></ul></td></tr>
        </table>   
      </div>
    </div>
    <div class="headBot"> 
     <div class="container">
      <h2>Bakery</h2><!-- the h1s are in individual pages -->
      
      
      <div class="social"> <!--links to social media-->
<a href="https://twitter.com/search?q=georgias%20cakes&src=typd&lang=en">
<img class="social__tw">
</a>

<a href="https://www.facebook.com/georgiascakesuk">
<img class="social__fb"> 
</a>

<a href="https://www.instagram.com/georgiascakes/">
<img class="social__in">
</a>
</div>
      <ul>
         <span class="linksContainer">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Cakes", items_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "Cart", cart_path  %></li>
        
         <% if user_signed_in? %>
                  
         <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
         <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
          <% else %>
         <li><%= link_to 'Register', new_user_registration_path %></li> 
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <% end %>
        </span>
    </ul>
    </div>
   </div>
  </div>
</header>

app/views/layouts/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<div class="search-label"><%= label_tag(:q, "Search For Cakes") %></div>
<div class="search-input"><%= text_field_tag(:q) %>
<%= submit_tag("Search") %></div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%=yield(:title) %> | Bakery</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header'%> 
    <div class="row">
      <%= yield %> 
      <%= render 'layouts/footer'%> 
    </div>
  </body>
</html>